name: Enhancement Request
description: Request a new feature or improvement.
title: "[ENHANCEMENT] "
labels: ["enhancement"]
projects: ["cattywampus"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or improved?
      placeholder: Describe the enhancement you'd like to see...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature help you or other users?
      placeholder: Explain why this would be useful...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information that might be helpful...
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Taco-Comovilla/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true